[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer"]

[phases.build]
cmds = ["composer install --no-dev", "php artisan optimize"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"